#' CoRecMotif class
#'
#' A container for motifs generated by a CoRec experiment.
#'
#' @slot probe_set a string specifying the probe set name.
#' @slot pbm_condition a string specifying the PBM condition (e.g., cell type,
#'   treatment, and factor profiled).
#' @slot zscore_motif a 4 x n numeric matrix of z-scores such as generated by
#'   [make_zscore_motif()].
#' @slot array_id a string specifying the particular array/experiment the
#'   z-score motif is from.
#' @slot motif_strength a number representing the motif strength. Calculated
#'   automatically. See 'Details' for more information
#' @slot rolling_ic a number representing the maximum average information
#'   content over a sliding window. Calculated automatically. See 'Details' for
#'   more information.
#' @slot seed_sequence a string specifying the sequence of the seed probe.
#' @slot beta a number used to convert the z-score motif to a PPM. Calculated
#'   automatically. See 'Details' for more information.
#' @slot ppm a [universalmotif][universalmotif::universalmotif-class]
#'   representing the PPM generated using the z-score motif. Calculated
#'   automatically. See 'Details' for more information.
#' @slot match_motif a [universalmotif][universalmotif::universalmotif-class]
#'   representing the best match reference motif or NULL if no match has been
#'   found.
#' @slot match_pvalue a number representing the adjusted p-value of the best
#'   match to a reference motif.
#' @slot match_cluster a string representing the cluster of the best match
#'   reference motif.
#'
#' @return An object of class `CoRecMotif`.
#'
#' @export
#'
#' @name CoRecMotif-class
#' @rdname CoRecMotif-class
setClass(
    # Name the class CoRecMotif
    "CoRecMotif",

    # Define the names and types of the slots the class should have
    slots = list(
        probe_set = "character",
        pbm_condition = "character",
        zscore_motif = "matrix",
        array_id = "character",
        motif_strength = "numeric",
        rolling_ic = "numeric",
        seed_sequence = "character",
        beta = "numeric",
        ppm = "ANY",
        match_motif = "ANY",
        match_pvalue = "numeric",
        match_cluster = "character"
    ),

    # Provide a default example object
    prototype = list(
        probe_set = NA_character_,
        pbm_condition = NA_character_,
        zscore_motif = matrix(NA_real_),
        array_id = NA_character_,
        motif_strength = NA_real_,
        rolling_ic = NA_real_,
        seed_sequence = NA_character_,
        beta = NA_real_,
        ppm = NULL,
        match_motif = NULL,
        match_pvalue = NA_real_,
        match_cluster = NA_character_
    )
)

#' Make a new CoRecMotif
#'
#' Create a CoRecMotif from a 4 x n matrix of z-scores.
#'
#' @param probe_set a string specifying the probe set name.
#' @param pbm_condition a string specifying the PBM condition (e.g., cell type,
#'   treatment, and factor profiled).
#' @param zscore_motif a 4 x n numeric matrix of z-scores such as generated by
#'   [make_zscore_motif()].
#' @param array_id a string specifying the particular array/experiment the
#'   z-score motif is from.
#' @param seed_sequence a string specifying the sequence of the seed probe.
#'
#' @return An object of class [CoRecMotif][CoRecMotif-class].
#'
#' @export
#'
#' @examples
#' print("FILL THIS IN")
CoRecMotif <-
    function(
        probe_set,
        pbm_condition,
        zscore_motif,
        array_id = NA_character_,
        seed_sequence = NA_character_
    ) {
        motif_name <- paste(probe_set, pbm_condition, sep = "_")

        motif_strength <- calculate_strength(zscore_motif)

        beta <- calculate_beta(zscore_motif)

        ppm <- zscore_to_ppm(zscore_motif, beta, motif_name)

        rolling_ic <- calculate_rolling_ic(ppm)

        methods::new(
            "CoRecMotif",
            probe_set = probe_set,
            pbm_condition = pbm_condition,
            zscore_motif = zscore_motif,
            array_id = array_id,
            beta = beta,
            motif_strength = motif_strength,
            rolling_ic = rolling_ic,
            seed_sequence = seed_sequence,
            ppm = ppm
        )
    }

setValidity("CoRecMotif", function(object) {
    if (length(object@probe_set) > 1) {
        "@probe_set has to be a character vector of length 1"
    } else if (!is(object@ppm, "universalmotif")) {
        "@ppm has to be an object of class universalmotif"
    } else if (!is(object@match_motif, "universalmotif") &&
               !is.null(object@match_motif)) {
        "@match_motif has to be an object of class universalmotif or NULL"
    } else {
        TRUE
    }
})
