#' CoRecMotif class
#'
#' A container for motifs generated by a CoRec experiment.
#'
#' @slot probe_set `character(1)`. The probe set name.
#' @slot pbm_condition `character(1)`. The PBM condition (e.g., cell type,
#'   treatment, and factor profiled).
#' @slot zscore_motif `matrix(numeric())`. The z-score motif. See
#'   [make_zscore_motif()] for a description of the expected format.
#' @slot array_id `character(1)`. The name of the array/experiment the z-score
#'   motif is from.
#' @slot motif_strength `numeric(1)`. Calculated automatically. The motif
#'   strength is the 93rd percentile of the z-scores in the z-score motif (or
#'   approximately the median of the top 15% of z-scores).
#' @slot rolling_ic `numeric(1)`. Calculated automatically. The rolling IC is
#'   the maximum value obtained when taking a moving average of the information
#'   content of the motif over a sliding window of length 5.
#' @slot seed_sequence `character(1)`. The sequence of the seed probe.
#' @slot beta `numeric(1)`. Calculated automatically. Beta is defined as \eqn{4
#'   - (0.5 * z)}, where `z` is the z-score of the seed probe of this probe set.
#'   If beta falls outside the range of 1 to 4 (inclusive), it is set to the
#'   nearest endpoint. It is used to convert the z-score motif to a PPM.
#' @slot ppm [universalmotif][universalmotif::universalmotif-class]. Calculated
#'   automatically. To convert the z-score motif into a PPM, each z-score is
#'   first multiplied by beta, and then the product is exponentiated. Each
#'   column (or position in the motif) is then normalized to sum to 1.
#' @slot match_motif [universalmotif][universalmotif::universalmotif-class]. The
#'   best match reference motif.
#' @slot match_pvalue `numeric(1)`. The adjusted p-value of the best match to a
#'   reference motif.
#' @slot match_cluster `character(1)`. The cluster of the best match reference
#'   motif.
#'
#' @export
#'
#' @name CoRecMotif-class
#' @rdname CoRecMotif-class
setClass(
    # Name the class CoRecMotif
    "CoRecMotif",

    # Define the names and types of the slots the class should have
    slots = list(
        probe_set = "character",
        pbm_condition = "character",
        zscore_motif = "matrix",
        array_id = "character",
        motif_strength = "numeric",
        rolling_ic = "numeric",
        seed_sequence = "character",
        beta = "numeric",
        ppm = "ANY",
        match_motif = "ANY",
        match_pvalue = "numeric",
        match_cluster = "character"
    ),

    # Provide a default example object
    prototype = list(
        probe_set = NA_character_,
        pbm_condition = NA_character_,
        zscore_motif = matrix(NA_real_),
        array_id = NA_character_,
        motif_strength = NA_real_,
        rolling_ic = NA_real_,
        seed_sequence = NA_character_,
        beta = NA_real_,
        ppm = NA,
        match_motif = NA,
        match_pvalue = NA_real_,
        match_cluster = NA_character_
    )
)

#' Create a CoRecMotif object
#'
#' Create a CoRecMotif from a 4 x n matrix of z-scores.
#'
#' @param probe_set `character(1)`. The probe set name.
#' @param pbm_condition `character(1)`. The PBM condition (e.g., cell type,
#'   treatment, and factor profiled).
#' @param zscore_motif `matrix(numeric())`. The z-score motif. See
#'   [make_zscore_motif()] for a description of the expected format.
#' @param array_id `character(1)`. The name of the array/experiment the z-score
#'   motif is from.
#' @param seed_sequence `character(1)`. The sequence of the seed probe.
#'   (Default: NA)
#'
#' @return An object of class [CoRecMotif][CoRecMotif-class].
#'
#' @export
#'
#' @examples
#' print("FILL THIS IN")
CoRecMotif <-
    function(
        probe_set,
        pbm_condition,
        zscore_motif,
        array_id,
        seed_sequence = NA_character_
    ) {
    motif_name <- paste(probe_set, pbm_condition, array_id, sep = "_")

    motif_strength <- calculate_strength(zscore_motif)

    beta <- calculate_beta(zscore_motif)

    ppm <- zscore_to_ppm(zscore_motif, beta, motif_name)

    rolling_ic <- calculate_rolling_ic(ppm)

    methods::new(
        "CoRecMotif",
        probe_set = probe_set,
        pbm_condition = pbm_condition,
        zscore_motif = zscore_motif,
        array_id = array_id,
        beta = beta,
        motif_strength = motif_strength,
        rolling_ic = rolling_ic,
        seed_sequence = seed_sequence,
        ppm = ppm
    )
}

setValidity("CoRecMotif", function(object) {
    if (length(object@probe_set) > 1) {
        "@probe_set has to be a character vector of length 1"
    } else if (!is(object@ppm, "universalmotif")) {
        "@ppm has to be an object of class universalmotif"
    } else if (!is(object@match_motif, "universalmotif") &&
               !is.na(object@match_motif)) {
        "@match_motif has to be an object of class universalmotif or NULL"
    } else {
        TRUE
    }
})
